### ISSUE TITLE
Won't strip ID v2 tags

### ISSUE THREAD

**Issue by gaelanlloyd** [impegoraro/tagtool#1]
Hi there, I've used this program for years in other distros (mainly Debian/Ubuntu) because it can easily strip out IDv2 tags.  When using this version for Arch from the AUR the program doesn't strip out the v2 tags.  Wondering if you could take a look at what may be causing this.  Let me know if I can help... Thanks!

**Comment by impegoraro** [comment]
Hi, I've been testing the program and I'm able to clear the IDv2 tags the bug, although I've found that after clearing the IDv2 tags the view is not updated automatically, you need to change to another file and change back. Please check again if that's what's happening.
By the way what version are you running ? I've tested against master

**Comment by gaelanlloyd** [comment]
When I download the package from the AUR it ends up installing version 0.13.4.  But, in the AUR page it shows version 0.14-1.

I tried to clear a V2 tag, save the file, and then switch to a new file and back...  I see the same behavior.  When switching back to the file where I cleared the V2 tag, the V2 tag editing tab still shows the "green dot" like there's an empty V2 tag in the file.

PS -- Thanks for such a fast response, I didn't expect to hear back from you so soon!

**Comment by impegoraro** [comment]
Hi sorry for not saying anything, I went on vacation but now I'm back. 

Well regarding the version issue that's my fault, I forgot to update the configure scripts before tagging the new version on git, I'll fix that soon.

Regarding the other issue I've tested what you just described with the fedora version which is the version before I started adding changes, and the issue remains, can you confirm that this does not happen on ubuntu nor debian? 

In any case I'll try to find out how to fix it.

Best regards

**Comment by gaelanlloyd** [comment]
Hey there, I have tested this on Debian 8.5 running tagtool v0.12.3, and it removes ID3v2 tags as expected.  I recorded my screen, showing:
- Removing ID3v2 tag manually from a file.
- Removing ID3v2 tag using the bulk "clear tags" feature from another file.

Here's the recording: https://youtu.be/9IXCgpHoQi4

Both files start with v1 and v2 tags, and both end up with only a v1 tag at the end.  When I do this with the version from the AUR, it doesn't end up removing the v2 tag.

**Comment by impegoraro** [comment]
Hey there, I think I have found a way to fix your issue, the problem was not in the file but in the UI, for some reason the library returns that the file contains the metadata when in fact there's no metadata.

I've tagged version 0.14.2, try it and let me know

**Comment by gaelanlloyd** [comment]
Just downloaded and compiled from source, and it seems to be working now!  Thanks for your help fixing this.

I see that you guys are moving the application to GTK3.  I'm using XFCE and the new look is missing the menu bar and window controls, so it's tough to resize the window or get access to the menu options.  Should I open another issue for that?

Here's what the program looks like on my machine.  It's cut-off on the right side and there's no menu bar (I didn't crop this image).

![tagtool](https://cloud.githubusercontent.com/assets/1403649/18060587/f31e4f02-6dd3-11e6-88e2-209781594e92.png)

**Comment by gaelanlloyd** [comment]
It's not much better in Gnome 3...  Still cut-off and missing window controls.  Moving the mouse over to the window edges don't allow me to resize the window.

![tagtool-gnome3](https://cloud.githubusercontent.com/assets/1403649/18060733/a6df8dbc-6dd4-11e6-9b45-d3e1738ad80b.png)

I know you guys are probably right in the middle of working on this, but wanted to give you the feedback anyway.  What I liked about this program was that you didn't need to run it full-screen, it could work even when the window was really small.  Now, with the new buttons using text instead of icons, everything is way bigger and the window needs to be super huge in order for the program to be useful.

**Comment by impegoraro** [comment]
Hi there, yup sorry I've been working on my spare time and I haven't finished the update yet, and I've realized that I've been working on the master branch, which is very bad for exactly this reason. Anyway tomorrow I'll fix all this, i'll move this work to the develop branch and leave master in a good state with the fix for this issue. 
Sorry for the inconvenience, and thanks for the feedback.
Feel free to open more issue has you see fit.

**Comment by impegoraro** [comment]
Actually was quite easy to backport to develop, try using that branch instead. if all goes well I'm closing this issue.

**Comment by gaelanlloyd** [comment]
Tested using the develop branch and the v2 tag deletion is working as expected now.  And, I see the original interface once again.

I think this is a candidate to release for an update to the AUR package.  Thanks for all of your help on this!
